////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2011 Bernard Badjari
//
// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use,
// copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following
// conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
// OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
//
////////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using VSFile.Properties;
using VSFile.Source;
using VSFile.System;

namespace VSFile.Project
{
	/// <summary>
	/// Represents a Visual Studio project file.
	/// </summary>
	/// <typeparam name="T">
	/// Type of Visual Studio source file referenced in this Visual Studio project file.
	/// </typeparam>
	public abstract class ProjectFile<T> : VisualStudioFile
		where T : SourceFile
	{
		/// <summary>
		/// Names of attributes in project file.
		/// </summary>
		private static class Attribute
		{
			public const string Include = "Include";
		}

		/// <summary>
		/// Names of elements in project file.
		/// </summary>
		private static class Element
		{
			public const string AutoGenerated = "AutoGen";
		}

		/// <summary>
		/// XPath expressions used to select elements in project file.
		/// </summary>
		private static class XPath
		{
			public const string CompileElement = "/msb:Project/msb:ItemGroup/msb:Compile";
		}

		/// <summary>
		/// Namespace used in project file.
		/// </summary>
		private const string Namespace = "http://schemas.microsoft.com/developer/msbuild/2003";

		/// <summary>
		/// Namespace prefix used in XPath expressions.
		/// </summary>
		private const string NamespacePrefix = "msb";

		////////////////////////////////////////////////////////////////////////

		private List<T> sourceFiles;

		////////////////////////////////////////////////////////////////////////
		// Constructors

		/// <summary>
		/// Internal constructor.
		/// </summary>
		/// <param name="projectName">
		/// String representing Visual Studio project name.
		/// </param>
		/// <param name="fileExtension">
		/// String representing file extension of Visual Studio project file.
		/// </param>
		/// <param name="filePath">
		/// String representing path to Visual Studio project file.
		/// </param>
		/// <param name="sourceFileExtension">
		/// String representing file extension of Visual Studio source files
		/// referenced in this Visual Studio project file.
		/// </param>
		/// <param name="xmlFileReader">
		/// IXmlFileReader instance representing XML file reader.
		/// </param>
		/// <param name="fileSystem">
		/// IFileSystem instance representing file system.
		/// </param>
		internal ProjectFile(string projectName, string fileExtension, string filePath, string sourceFileExtension, IXmlFileReader xmlFileReader, IFileSystem fileSystem)
			: base(fileExtension, filePath, fileSystem)
		{
			if (string.IsNullOrWhiteSpace(sourceFileExtension))
				throw new ArgumentException(ExceptionMessages.InvalidSourceFileExtension);

			if (xmlFileReader == null)
				throw new ArgumentNullException("xmlFileReader");

			ProjectName = string.IsNullOrWhiteSpace(projectName) ? FileNameNoExtension : projectName;
			SourceFileExtension = sourceFileExtension;
			sourceFiles = new List<T>();
			XmlFileReader = xmlFileReader;
		}

		/// <summary>
		/// Constructor for specifying file path.
		/// </summary>
		/// <param name="fileExtension">
		/// String representing file extension of Visual Studio project file.
		/// </param>
		/// <param name="filePath">
		/// String representing path to Visual Studio project file.
		/// </param>
		/// <param name="sourceFileExtension">
		/// String representing file extension of Visual Studio source files
		/// referenced in this Visual Studio project file.
		/// </param>
		protected ProjectFile(string fileExtension, string filePath, string sourceFileExtension)
			: this(null, fileExtension, filePath, sourceFileExtension)
		{
		}

		/// <summary>
		/// Constructor for specifying project name.
		/// </summary>
		/// <param name="projectName">
		/// String representing Visual Studio project name.
		/// </param>
		/// <param name="fileExtension">
		/// String representing file extension of Visual Studio project file.
		/// </param>
		/// <param name="filePath">
		/// String representing path to Visual Studio project file.
		/// </param>
		/// <param name="sourceFileExtension">
		/// String representing file extension of Visual Studio source files
		/// referenced in this Visual Studio project file.
		/// </param>
		protected ProjectFile(string projectName, string fileExtension, string filePath, string sourceFileExtension)
			: this(projectName, fileExtension, filePath, sourceFileExtension, new XmlFileReader(), new FileSystem())
		{
		}

		////////////////////////////////////////////////////////////////////////
		// Methods

		/// <summary>
		/// Create instance of source file with given file path.
		/// </summary>
		/// <param name="filePath">
		/// String representing file path.
		/// </param>
		/// <returns>
		/// Instance of source file with given file path.
		/// </returns>
		protected abstract T CreateSourceFile(string filePath);

		/// <summary>
		/// Read file.
		/// </summary>
		protected override void ReadFile()
		{
			ClearFiles();

			XDocument document = XmlFileReader.Load(FilePath);

			XmlNamespaceManager namespaceManager = new XmlNamespaceManager(new NameTable());

			namespaceManager.AddNamespace(NamespacePrefix, Namespace);

			IEnumerable<XElement> elements = document.XPathSelectElements(XPath.CompileElement, namespaceManager);

			foreach (XElement element in elements)
				AddSourceFile(element);
		}

		/// <summary>
		/// Add source file contained within given XML element.
		/// </summary>
		/// <param name="element">
		/// XElement containing source file.
		/// </param>
		private void AddSourceFile(XElement element)
		{
			XElement autoGeneratedElement = element.Element(Element.AutoGenerated);

			if (autoGeneratedElement != null)
			{
				string autoGenerated = autoGeneratedElement.Value;

				// Ignore auto-generated files.
				if (!string.IsNullOrWhiteSpace(autoGenerated) && autoGenerated.Equals(bool.TrueString, StringComparison.OrdinalIgnoreCase))
					return;
			}

			XAttribute includeAttribute = element.Attribute(Attribute.Include);

			if (includeAttribute != null)
			{
				string filePath = includeAttribute.Value;

				if (!string.IsNullOrWhiteSpace(filePath) && filePath.EndsWith(SourceFileExtension, StringComparison.OrdinalIgnoreCase))
				{
					T sourceFile = CreateSourceFile(GetFullPath(filePath));

					sourceFiles.Add(sourceFile);
				}
			}
		}

		/// <summary>
		/// Clear referenced source files.
		/// </summary>
		private void ClearFiles()
		{
			sourceFiles.Clear();
		}

		////////////////////////////////////////////////////////////////////////
		// Properties

		/// <summary>
		/// Get project name.
		/// </summary>
		/// <value>
		/// String representing project name.
		/// </value>
		public string ProjectName { get; private set; }

		/// <summary>
		/// Get file extension of Visual Studio source files referenced in this project file.
		/// </summary>
		/// <value>
		/// String representing Visual Studio source file extension.
		/// </value>
		public string SourceFileExtension { get; private set; }

		/// <summary>
		/// Get Visual Studio source files referenced in this project file.
		/// </summary>
		/// <value>
		/// Enumerable collection of objects representing Visual Studio source
		/// files referenced in this project file.
		/// </value>
		public IEnumerable<T> SourceFiles
		{
			get { return sourceFiles; }
		}

		/// <summary>
		/// Get/set XML file reader.
		/// </summary>
		/// <value>
		/// IXmlFileReader instance representing XML file reader.
		/// </value>
		private IXmlFileReader XmlFileReader { get; set; }
	}
}
