//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSFile.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmbeddedFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmbeddedFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSFile.Tests.Properties.EmbeddedFiles", typeof(EmbeddedFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicProjectFile {
            get {
                return ResourceManager.GetString("BasicProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Class BasicSourceFile
        ///
        ///End Class
        ///.
        /// </summary>
        internal static string BasicSourceFile {
            get {
                return ResourceManager.GetString("BasicSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSharpProjectFile {
            get {
                return ResourceManager.GetString("CSharpProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace CSharpProjectFile
        ///{
        ///	public class CSharpSourceFile
        ///	{
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string CSharpSourceFile {
            get {
                return ResourceManager.GetString("CSharpSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;12.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;Import Project=&quot;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&quot; Condition=&quot;Exists(&apos;$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props&apos;)&quot; /&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FSharpProjectFile {
            get {
                return ResourceManager.GetString("FSharpProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to module FSharpSourceFile
        ///.
        /// </summary>
        internal static string FSharpSourceFile {
            get {
                return ResourceManager.GetString("FSharpSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 2013
        ///VisualStudioVersion = 12.0.40629.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{F184B08F-C81C-45F6-A57F-5ABD9991F28F}&quot;) = &quot;BasicProjectFile&quot;, &quot;BasicProjectFile.vbproj&quot;, &quot;{719BD374-47FE-4078-B07E-FB9DF49274BB}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;CSharpProjectFile&quot;, &quot;CSharpProjectFile.csproj&quot;, &quot;{906335D9-9DAB-4D38-ACF7-42C57FE07EC9}&quot;
        ///EndProject
        ///Project(&quot;{F2A71F9B-5D33-465A-A702-920D77 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolutionFile {
            get {
                return ResourceManager.GetString("SolutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 
        ///# Visual Studio 2013
        ///VisualStudioVersion = 12.0.40629.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{F184B08F-C81C-45F6-A57F-5ABD9991F28F}&quot;) = &quot;BasicProjectFile&quot;, &quot;BasicProjectFile.vbproj&quot;, &quot;{719BD374-47FE-4078-B07E-FB9DF49274BB}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;CSharpProjectFile&quot;, &quot;CSharpProjectFile.csproj&quot;, &quot;{906335D9-9DAB-4D38-ACF7-42C57FE07EC9}&quot;
        ///EndProject
        ///Project(&quot;{F2A71F9B-5D33-465A-A702-920D7727978 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolutionFileInvalidHeader {
            get {
                return ResourceManager.GetString("SolutionFileInvalidHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///# Visual Studio 2013
        ///VisualStudioVersion = 12.0.40629.0
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{F184B08F-C81C-45F6-A57F-5ABD9991F28F}&quot;) = &quot;BasicProjectFile&quot;, &quot;BasicProjectFile.vbproj&quot;, &quot;{719BD374-47FE-4078-B07E-FB9DF49274BB}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;CSharpProjectFile&quot;, &quot;CSharpProjectFile.csproj&quot;, &quot;{906335D9-9DAB-4D38-ACF7-42C57FE07EC9}&quot;
        ///EndProject
        ///Project(&quot;{F2A71F9B-5D33-465A-A702-920D77279786}&quot;) = &quot;FSharpProjectFile&quot;, &quot;FSharpProjectFile.fsproj&quot;,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolutionFileNoHeader {
            get {
                return ResourceManager.GetString("SolutionFileNoHeader", resourceCulture);
            }
        }
    }
}
