name: GitHub Action For .NET

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-then-test:
        runs-on: windows-latest

        env:
            CONFIGURATION: Release
            CONSOLE_RUNNER_VERSION: 3.12.0
            SOLUTION_FILE: VSFile.sln
            TEST_PROJECT: VSFile.Tests

        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET 5.0
          uses: actions/setup-dotnet@v1
          with:
              dotnet-version: 5.0.x

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5

        - name: Restore Packages
          run: nuget restore ${env:SOLUTION_FILE}

        - name: Build Solution
          run: dotnet build --configuration ${env:CONFIGURATION} ${env:SOLUTION_FILE}

        - name: Install NUnit.ConsoleRunner Package
          run: nuget install NUnit.ConsoleRunner -Version ${env:CONSOLE_RUNNER_VERSION}

        - name: Run NUnit Tests
          run: Packages\NUnit.ConsoleRunner.${env:CONSOLE_RUNNER_VERSION}\tools\nunit3-console.exe ${env:TEST_PROJECT}\bin\${env:CONFIGURATION}\${env:TEST_PROJECT}.dll
